### ISSUE TITLE
Documentation: Typo in EDTV Video details

### ISSUE THREAD

**Issue by bradriley** [chriz2600/DreamcastHDMI#1]
https://rawgit.com/chriz2600/DreamcastHDMI/master/assets/video.html

"720p EDTV" is nonsensical, of course, as 1280x720p is HDTV.

Perhaps the line was meant to read "720x480p EDTV".

Also, "may be also" in the final paragraph would reat easier as "may also be" IMO.

**Comment by chriz2600** [comment]
Yes, it should be 480p, not 720p. Thank you!
