### ISSUE TITLE
SPDIF output?

### ISSUE THREAD

**Issue by pcercuei** [chriz2600/DreamcastHDMI#10]
Does the FPGA convert the digital audio to SPDIF to get it to the ADV7315?
If so, it'd be great to have solder pads somewhere, so that a Toslink or RCA connector for SPDIF can be added.

**Comment by chriz2600** [comment]
Digital audio goes directly to the ADV7513. The audio output of AICA is [I2S](https://en.wikipedia.org/wiki/I%C2%B2S). So an external audio transmitter would be required to convert I2S to S/PDIF (IEC-60958), e.g. [http://www.ti.com/lit/ds/symlink/dit4096.pdf](http://www.ti.com/lit/ds/symlink/dit4096.pdf)
You could also use an [HDMI audio extractor](https://www.amazon.com/AmazonBasics-Audio-Extractor-Konverter-Audio-SPDIF-Stereo/dp/B07KRWYN4R) to get S/PDIF from HDMI.

**Comment by pcercuei** [comment]
Right now I do it with a CS8406, see https://gamesx.com/wiki/doku.php?id=av:dreamcastda

If you have 4 pads connected to free pins on the FPGA, I could try to make a I2S to SPDIF IP.

**Comment by chriz2600** [comment]
That would be awesome, but unfortunately in the current design we are out of output pins. There are only some clock inputs left (which could be used as user input pins).
I attached a PDF showing all used pins:
- Grey: used by DCHDMI
- Green: used for SPI flash configuration
- Violet: FPGA config pins
- Orange: JTAG
- White: free pins (except all power related pins at the bottom of the list)

[10cl025 DCHDMI.pdf](https://github.com/chriz2600/DreamcastHDMI/files/3855990/10cl025.DCHDMI.pdf)

**Comment by pcercuei** [comment]
So we're just short of one output pin? That sucks xD
