### ISSUE TITLE
Web console outputs "Error reading original checksum" after OSD update but OSD is OK

### ISSUE THREAD

**Issue by aaron-clovsky** [chriz2600/DreamcastHDMI#11]
I just got one of the DCHDMI round 11 kits and installed it, everything went fine and it looks amazing! 

I set up WiFi on the OSD and checked for available updates and found 4.3, downloaded and flashed it. Afterwards the OSD still reads 4.2-std, but checking for updates shows I have the latest.

I then went into the web console and ran setup and then ran "check" which outputs "Error reading original checksum".

Going back to download or flash in the OSD shows, "file already downloaded" and "file already flashed". 

https://imgur.com/a/dP2eUki

Nothing's broken or anything, but I am a bit confused.

**Comment by chriz2600** [comment]
Please use the `cleanup` command on the web console to remove all firmware update files before updating again (thru OSD or web console). 
This will force a re-download and re-flashing. Consider this a workaround at this point, I'm still trying to replicate this issue.

**Comment by aaron-clovsky** [comment]
So if I run cleanup then download then flash it should redownload and reflash the firmware? I was a little concerned by the previous version number being displayed, so I just want to make sure I'm in a good state.

**Comment by chriz2600** [comment]
Yes, running `cleanup` followed by `download` and `flash` will make sure your firmware is fully updated to v4.3. As long as the OSD shows 4.2, at least the ESP part of the firmware was not upgraded.
If you do the update from the web console, you have to make sure that both your browser and dreamcast can access the internet.
The `Error reading original checksum` you got indicates that the browser was not able to fetch the firmware checksum for comparison with the last flashed version.

**Comment by aaron-clovsky** [comment]
Thank you! that makes much more sense! I did try on both Chrome and Firefox, but I did not bother checking the dev console output since I (obviously incorrectly) assumed that the check would be performed by the DCHDMI itself.

https://imgur.com/a/6f63jL6

Tracking the output in the consoles of both browsers I can see it attempting to use the URL:

http://dc.i74.deundefined/fw/master/DCxPlus-v2.dc.md5?cc=0.6570458337522258

while the correct URL is clearly:

http://dc.i74.de/fw/master/DCxPlus-v2.dc.md5?cc=0.6570458337522258

If it helps any my config output (SSID and passwords redacted) is:

https://imgur.com/a/0nJwchN

After my initial setup on the OSD I did run the web console setup command.

So at this point it looks like I should run cleanup on the console then do the firmware update from the OSD?

**Comment by chriz2600** [comment]
Yes, the "undefined" value confirms, that your index.html file for the web console is already on v4.3, while the ESP firmware is still on v4.2. (There is a new config item introduced with v4.3, which is missing on v4.2, thus the broken URI). There must have been some undetected error while updating the ESP firmware, a `cleanup` followed by a firmware update via the OSD should fix this.

**Comment by aaron-clovsky** [comment]
Thank you so much for the help! I ran `cleanup` then updated again via the OSD and now both the OSD and web console are reporting v4.3-std.
