### ISSUE TITLE
Feature Request: Add MODE as reset option

### ISSUE THREAD

**Issue by mobiusstriptech** [chriz2600/DreamcastHDMI#13]
With the TerraOnion MODE release on the horizon, adding it to the reset options would be beneficial to end users.

The reset type is the same as the GDEMU reset. This means the change is mostly cosmetic but still beneficial for user experience.

A special pin was added on MODE specifically to allow easy connection to DCDigital via JST XH 9pin connector. This option is specifically just for controlling disc switching. The DCDigital standard system reset is already supported by MODE and returns to menu or reboots game depending on user options. If there are any questions, please let me know. I would be happy to help.

**Comment by chriz2600** [comment]
Ok, great!

So I will add a "MODE" option to the web console setup's "Opt. reset mode" setting.
The menu will then show:
`Y: MODE disc switch`

Correct?

**Comment by mobiusstriptech** [comment]
Yes sir. That would be perfect. I didn't look at the code but I assume it's an enumeration addition. So hopefully very low complexity.

**Comment by chriz2600** [comment]
No worries, it's easy to add :)

**Comment by chriz2600** [comment]
Added in 135135b
This is currently on the `develop` branch, if you like to test :)

**Comment by mobiusstriptech** [comment]
Yes absolutely. Thank you.

**Comment by mobiusstriptech** [comment]
I loaded the develop branch and can see the changelog stating it was added. It looks like the option hasn't been added as a valid option in the setup. Is there a way to force it?

**Comment by chriz2600** [comment]
Please try to do empty your browser cache and then reload the web console.

**Comment by mobiusstriptech** [comment]
My apologies. That did work. I was able to see and set it to mode. I can confirm that the disc switching is working as well. Thank you very much!

**Comment by chriz2600** [comment]
Cool!
