### ISSUE TITLE
DC Digital takes very long to display any image when it can't connect to the wifi network

### ISSUE THREAD

**Issue by mathieulh** [chriz2600/DreamcastHDMI#17]
If you define a wifi network on DC Digital and it can't connect to it somehow (happens a lot with the ESP8266 wifi stack and ASUS routers as threre is a known incompatibility issue), the DC Digital takes very long (about a full minute) to display any image when it can't connect to the wifi network when cold booting the Dreamcast.

**Comment by chriz2600** [comment]
New version 4.9 initialises the WiFi connection asynchronously, so it should not slow down the startup sequence.
If you want to test the new firmware, configure `develop` as firmware version during web console `setup` (`6/19: Firmware Version`)

**Comment by mathieulh** [comment]
Thanks, I updated it, I will see how it goes (it currently connects fine as I rebooted the router minutes ago)

**Comment by mathieulh** [comment]
Ok, I can say that this does work as intended, in fact it makes cold booting slightly faster (about 2 seconds faster even when wifi connects fine) overall.
