### ISSUE TITLE
Adding support for Motion Adaptive Deinterlace

### ISSUE THREAD

**Issue by mathieulh** [chriz2600/DreamcastHDMI#18]
I would like to know if it's possible to add support for Motion Adaptive Deinterlace, I know this adds one frame of lag, but the result looks much cleaner than bob deinterlace as it has no flickering of any kind and no combing artifacts, making 480i upscale to what looks like a slightly softer 480p.

If you want to know what Motion Adaptive Deinterlace looks like, take a closer look at GBS Control which implements it.

**Comment by chriz2600** [comment]
Motion Adaptive Deinterlacing isn't possible with the current hardware. It does not have the required RAM resources for the frame buffer needed.
