### ISSUE TITLE
Problem in v3.0.0 HQ2x implementation with scanline enabled

### ISSUE THREAD

**Issue by SONIC3D** [chriz2600/DreamcastHDMI#2]
Hi, chriz2600:

I think there is a problem in v3.0.0 HQ2x implementation. The HQ2x pass seems applied after the scanline effect pass. So the effect is not correct if HQ2x and scanline are both enabled. It looks like the color gradient is wrong like 16bit color or 8bit color. But I think it's actually the  interpolation progress is affected by the scanline color.

You can check the wrong effect from my tutorial video. Time code [2:38:32 - 2:40:00]. 
https://www.youtube.com/watch?v=GoH0m_2MEcI

**Comment by chriz2600** [comment]
Yeah, you're right. I will release a new firmware fixing this in a couple of days.

**Comment by SONIC3D** [comment]
Thanks a lot. =)

**Comment by chriz2600** [comment]
Firmware Release v3.0.2 was released yesterday.
