### ISSUE TITLE
VGA mode is no longer compliant with LG screens

### ISSUE THREAD

**Issue by mobiusstriptech** [chriz2600/DreamcastHDMI#3]
The default VGA mode with cable detect is now causing issues with LG TVs. Previous firmware did not have this issue and functioned normally. This issue would be solvable if the WiFi password was static and not dynamic or there was a way to access this without using the OSD.

This issue has been confirmed on a 65C9 OLED, 65G7 OLED, and a 10 year old LG 21" LCD TV. The 10 year old TV does not have the ability to perform firmware updates and is stuck on the factory firmware.

**Comment by mobiusstriptech** [comment]
Also found this issue on the following TV's.

Sony XBR75850D 4K
Toshiba 46SV670U

Both of these work if you change from VGA to another resolution and save. The LG OLED C9 also will work as long as it's not VGA. The G7 will not work at all.

**Comment by chriz2600** [comment]
There was a bug in the initialization sequence occurring when the output resolution was set to _**VGA**_ and the video mode was set to _**Cable Detect**_, which resulted in no image being shown. This is fixed and will be released to the firmware update server soon. Version is v2.3.3 for _standard_ and v3.0.3 for _relaxed_.

**Comment by mobiusstriptech** [comment]
This is no longer occurring in v2.3.4 and v3.0.4.
