### ISSUE TITLE
Please add support for PAL 288p video output

### ISSUE THREAD

**Issue by rdaviesuk** [chriz2600/DreamcastHDMI#5]
This affects most PAL low-res games.

In particular, the PAL version of Bangaio boots in 288p mode before offering 60Hz selection, and also doesn't support VGA mode.

In 288p mode the OSSC reports 313 lines.

Thanks.

**Comment by chriz2600** [comment]
Good point, 288p support will be added to the next firmware version.

**Comment by rdaviesuk** [comment]
That would be great, thanks.

**Comment by chriz2600** [comment]
288p output added in upcoming v4.0, which is in testing right now.
For a complete list of changes, see: [Firmware v4.0](https://github.com/chriz2600/DreamcastHDMI/tree/experimental#2019-08-25-firmware-v40-unified)

**Comment by chriz2600** [comment]
v4.0 was released today.
