### ISSUE TITLE
Please allow differing deinterlacing method for 480i/576i

### ISSUE THREAD

**Issue by rdaviesuk** [chriz2600/DreamcastHDMI#6]
My TV does a much better job of deinterlacing 576i than it does 480i, so allowing to configure the deinterlacing method separately for each would be really useful.

Thanks.

**Comment by chriz2600** [comment]
Good idea, will also be added in the next firmware version.

**Comment by rdaviesuk** [comment]
Great, thanks.

**Comment by chriz2600** [comment]
Separate configuration for 480i and 576i deinterlacing is part of upcoming v4.0, which is in testing right now.
For a complete list of changes, see: [Firmware v4.0](https://github.com/chriz2600/DreamcastHDMI/tree/experimental#2019-08-25-firmware-v40-unified)

**Comment by chriz2600** [comment]
v4.0 was released today.
