### ISSUE TITLE
HDMI-CEC compatibility

### ISSUE THREAD

**Issue by RobertDaleSmith** [chriz2600/DreamcastHDMI#8]
I'm sure this is something you have already considered but I was curious if it was possible to implement CEC support?

It would be so cool to auto power-on my TV when Dreamcast turns on or to control the DCHDMI's OSD with my TV's remote control.

**Comment by chriz2600** [comment]
Good idea! Unfortunately this would require a new DCHDMI board revision, as currently CEC is not connected.
