### ISSUE TITLE
Arduino MKR Vidor 4000 port?

### ISSUE THREAD

**Issue by Anarky** [chriz2600/DreamcastHDMI#9]
Hello, I just found the [Arduino MKR Vidor 4000](https://store.arduino.cc/mkr-vidor-4000).
It is a ~75€ board with a 10CL016, a Cortex-M0, 47 pins (25 are from the mini PCI express), a micro HDMI and Wifi & BLE.
Do you think it would be possible to port DCHDMI on it?

Also the [960p framed in 1080p mode](https://github.com/chriz2600/DreamcastHDMI/#cylcone-10-lp-10cl025) depends of a specific fonctionnality by the FPGA, or the small Cortex could help on some level?

**Comment by chriz2600** [comment]
Let's see:
- The HDMI TMDS encoding had to be done on the FPGA (HDMI is directly connected to the FPGA on the Vidor), there is no HDMI transmitter on the vidor. Code for that is available here: [https://github.com/chriz2600/DreamcastHDMI/tree/v0.1](https://github.com/chriz2600/DreamcastHDMI/tree/v0.1l), but this version only supports 480p output and is nothing more than an early prototype.
- The 960p in 1080p framed mode needs the additional on-chip memory of the 10CL25. The vidor board has external SDRAM, so this may be used to do the buffering.
- ESP8266 code had to be ported to the Cortex-M0.

I think it should be possible, but is a lot of work, so good luck :)
